name: Auto Connect Zenhub

on:
  pull_request:
    types: [opened, edited]

jobs:
  call_zenhub_connector:
    uses: shinzonetwork/docs/.github/workflows/zenhub-connect.yml@main
    secrets:
      ZENHUB_API_KEY: ${{ secrets.ZENHUB_API_KEY }}  
